export { default as home } from './home.vue'
export { default as shape } from './shape.vue'
export { default as signout } from './signout.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
